# Generated by Django 5.0.2 on 2024-02-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_members',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(to='products.employee'),
        ),
    ]
